image: docker:latest

cache:
  paths:
    - ./frontend-dev/node_modules/
    - ./frontend-server/node_modules/
    - $CI_PROJECT_DIR/cache

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/cache/.m2/repository"

stages:
  - test
  - build
  - deploy

backend-test:
  image: maven:3.6.0-jdk-11
  stage: test
  artifacts:
    expire_in: 1 week
    paths:
      - ./backend/target/surfire-reports
    when: on_failure
  script:
    - cd backend
    - mvn test
  tags:
    - docker

backend-build:
  image: maven:3.6.0-jdk-11
  stage: build
  artifacts:
    expire_in: 1 week
    paths:
      - ./backend/target/*.jar
  script:
    - cd backend
    - mvn package -DskipTests
  tags:
    - docker

backend-deploy-docker:
  image: docker:latest
  stage: deploy
  script:
    - cd backend
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.fme.de
    - ./mvnw install dockerfile:build
    - ./mvnw dockerfile:push
  tags:
    - docker

frontend-build:
  image: node:latest
  stage: build
  artifacts:
    expire_in: 1 week
    paths:
      - ./frontend-server/public
  script:
    - cd frontend-dev
    - npm install
    - npm run build || true #true, because build will "fail"
  tags:
    - docker

frontend-deploy-docker:
  image: docker:latest
  stage: deploy
  before_script:
    - echo "build will be plattform-dependent!"
  script:
    - cd frontend-server
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.fme.de
    - docker build -t docker.fme.de/r.vitt/bsc/frontend .
    - docker push docker.fme.de/r.vitt/bsc/frontend
  tags:
    - docker
