cache:
  paths:
  - ./frontend-dev/node_modules/
  - ./frontend-server/node_modules/

services:
- docker:dind

stages:
- build
- deploy

build:
  image: node:latest
  stage: build
  artifacts:
    expire_in: 1 week
    paths:
    - ./frontend-server/public
  script:
  - cd frontend-dev
  - npm install
  - npm run build || true #true, because build will "fail"
  tags:
  - docker

deploy-docker:
  image: docker:latest
  stage: deploy
  script:
  - cd frontend-server
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.rubeen.me
  - docker build -t docker.rubeen.me/studium/bsc/frontend .
  - docker push docker.rubeen.me/studium/bsc/frontend
  tags:
  - docker
