/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db.tables.records;


import de.rubeen.bsc.entities.db.tables.Appuser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppuserRecord extends UpdatableRecordImpl<AppuserRecord> implements Record6<Integer, String, String, String, String, String> {

    private static final long serialVersionUID = 1902071873;

    /**
     * Setter for <code>public.appuser.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.appuser.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.appuser.password</code>.
     */
    public void setPassword(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.appuser.password</code>.
     */
    public String getPassword() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.appuser.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.appuser.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.appuser.mail</code>.
     */
    public void setMail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.appuser.mail</code>.
     */
    public String getMail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.appuser.position</code>.
     */
    public void setPosition(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.appuser.position</code>.
     */
    public String getPosition() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.appuser.avatar</code>.
     */
    public void setAvatar(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.appuser.avatar</code>.
     */
    public String getAvatar() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Appuser.APPUSER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Appuser.APPUSER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Appuser.APPUSER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Appuser.APPUSER.MAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Appuser.APPUSER.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Appuser.APPUSER.AVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppuserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppuserRecord value2(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppuserRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppuserRecord value4(String value) {
        setMail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppuserRecord value5(String value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppuserRecord value6(String value) {
        setAvatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppuserRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppuserRecord
     */
    public AppuserRecord() {
        super(Appuser.APPUSER);
    }

    /**
     * Create a detached, initialised AppuserRecord
     */
    public AppuserRecord(Integer id, String password, String name, String mail, String position, String avatar) {
        super(Appuser.APPUSER);

        set(0, id);
        set(1, password);
        set(2, name);
        set(3, mail);
        set(4, position);
        set(5, avatar);
    }
}
