/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db.tables.records;


import de.rubeen.bsc.entities.db.enums.Calprovider;
import de.rubeen.bsc.entities.db.tables.Calendar;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CalendarRecord extends UpdatableRecordImpl<CalendarRecord> implements Record5<Integer, String, Boolean, Calprovider, Integer> {

    private static final long serialVersionUID = -626167043;

    /**
     * Setter for <code>public.calendar.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.calendar.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.calendar.calendarid</code>.
     */
    public void setCalendarid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.calendar.calendarid</code>.
     */
    public String getCalendarid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.calendar.activated</code>.
     */
    public void setActivated(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.calendar.activated</code>.
     */
    public Boolean getActivated() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.calendar.provider</code>.
     */
    public void setProvider(Calprovider value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.calendar.provider</code>.
     */
    public Calprovider getProvider() {
        return (Calprovider) get(3);
    }

    /**
     * Setter for <code>public.calendar.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.calendar.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Boolean, Calprovider, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Boolean, Calprovider, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Calendar.CALENDAR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Calendar.CALENDAR.CALENDARID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return Calendar.CALENDAR.ACTIVATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Calprovider> field4() {
        return Calendar.CALENDAR.PROVIDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Calendar.CALENDAR.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCalendarid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component3() {
        return getActivated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Calprovider component4() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCalendarid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getActivated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Calprovider value4() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CalendarRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CalendarRecord value2(String value) {
        setCalendarid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CalendarRecord value3(Boolean value) {
        setActivated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CalendarRecord value4(Calprovider value) {
        setProvider(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CalendarRecord value5(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CalendarRecord values(Integer value1, String value2, Boolean value3, Calprovider value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CalendarRecord
     */
    public CalendarRecord() {
        super(Calendar.CALENDAR);
    }

    /**
     * Create a detached, initialised CalendarRecord
     */
    public CalendarRecord(Integer id, String calendarid, Boolean activated, Calprovider provider, Integer userId) {
        super(Calendar.CALENDAR);

        set(0, id);
        set(1, calendarid);
        set(2, activated);
        set(3, provider);
        set(4, userId);
    }
}
