/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db.tables.records;


import de.rubeen.bsc.entities.db.tables.Credential;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CredentialRecord extends UpdatableRecordImpl<CredentialRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1742168317;

    /**
     * Setter for <code>public.credential.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.credential.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.credential.credential</code>.
     */
    public void setCredential(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.credential.credential</code>.
     */
    public String getCredential() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.credential.users_id</code>.
     */
    public void setUsersId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.credential.users_id</code>.
     */
    public Integer getUsersId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Credential.CREDENTIAL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Credential.CREDENTIAL.CREDENTIAL_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Credential.CREDENTIAL.USERS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCredential();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getUsersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCredential();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUsersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CredentialRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CredentialRecord value2(String value) {
        setCredential(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CredentialRecord value3(Integer value) {
        setUsersId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CredentialRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CredentialRecord
     */
    public CredentialRecord() {
        super(Credential.CREDENTIAL);
    }

    /**
     * Create a detached, initialised CredentialRecord
     */
    public CredentialRecord(Integer id, String credential, Integer usersId) {
        super(Credential.CREDENTIAL);

        set(0, id);
        set(1, credential);
        set(2, usersId);
    }
}
