/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db.tables.records;


import de.rubeen.bsc.entities.db.enums.Calprovider;
import de.rubeen.bsc.entities.db.tables.Credential;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CredentialRecord extends UpdatableRecordImpl<CredentialRecord> implements Record3<Integer, String, Calprovider> {

    private static final long serialVersionUID = 1009874023;

    /**
     * Setter for <code>public.credential.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.credential.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.credential.credential</code>.
     */
    public void setCredential(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.credential.credential</code>.
     */
    public String getCredential() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.credential.provider</code>.
     */
    public void setProvider(Calprovider value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.credential.provider</code>.
     */
    public Calprovider getProvider() {
        return (Calprovider) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Calprovider> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Calprovider> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Credential.CREDENTIAL.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Credential.CREDENTIAL.CREDENTIAL_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Calprovider> field3() {
        return Credential.CREDENTIAL.PROVIDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCredential();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Calprovider component3() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCredential();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Calprovider value3() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CredentialRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CredentialRecord value2(String value) {
        setCredential(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CredentialRecord value3(Calprovider value) {
        setProvider(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CredentialRecord values(Integer value1, String value2, Calprovider value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CredentialRecord
     */
    public CredentialRecord() {
        super(Credential.CREDENTIAL);
    }

    /**
     * Create a detached, initialised CredentialRecord
     */
    public CredentialRecord(Integer userId, String credential, Calprovider provider) {
        super(Credential.CREDENTIAL);

        set(0, userId);
        set(1, credential);
        set(2, provider);
    }
}
