/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db.tables.records;


import de.rubeen.bsc.entities.db.tables.RoomRoomEquipment;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomRoomEquipmentRecord extends UpdatableRecordImpl<RoomRoomEquipmentRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1878363165;

    /**
     * Setter for <code>public.room_room_equipment.room_id</code>.
     */
    public void setRoomId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.room_room_equipment.room_id</code>.
     */
    public Integer getRoomId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.room_room_equipment.room_equipment_id</code>.
     */
    public void setRoomEquipmentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.room_room_equipment.room_equipment_id</code>.
     */
    public Integer getRoomEquipmentId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RoomRoomEquipment.ROOM_ROOM_EQUIPMENT.ROOM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RoomRoomEquipment.ROOM_ROOM_EQUIPMENT.ROOM_EQUIPMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getRoomId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRoomEquipmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRoomId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRoomEquipmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomRoomEquipmentRecord value1(Integer value) {
        setRoomId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomRoomEquipmentRecord value2(Integer value) {
        setRoomEquipmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomRoomEquipmentRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoomRoomEquipmentRecord
     */
    public RoomRoomEquipmentRecord() {
        super(RoomRoomEquipment.ROOM_ROOM_EQUIPMENT);
    }

    /**
     * Create a detached, initialised RoomRoomEquipmentRecord
     */
    public RoomRoomEquipmentRecord(Integer roomId, Integer roomEquipmentId) {
        super(RoomRoomEquipment.ROOM_ROOM_EQUIPMENT);

        set(0, roomId);
        set(1, roomEquipmentId);
    }
}
