/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db.tables.records;


import de.rubeen.bsc.entities.db.tables.RoomEquipment;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomEquipmentRecord extends UpdatableRecordImpl<RoomEquipmentRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -572142049;

    /**
     * Setter for <code>public.room_equipment.equip_id</code>.
     */
    public void setEquipId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.room_equipment.equip_id</code>.
     */
    public Integer getEquipId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.room_equipment.equip_name</code>.
     */
    public void setEquipName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.room_equipment.equip_name</code>.
     */
    public String getEquipName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RoomEquipment.ROOM_EQUIPMENT.EQUIP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RoomEquipment.ROOM_EQUIPMENT.EQUIP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getEquipId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEquipName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEquipId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEquipName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomEquipmentRecord value1(Integer value) {
        setEquipId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomEquipmentRecord value2(String value) {
        setEquipName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomEquipmentRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoomEquipmentRecord
     */
    public RoomEquipmentRecord() {
        super(RoomEquipment.ROOM_EQUIPMENT);
    }

    /**
     * Create a detached, initialised RoomEquipmentRecord
     */
    public RoomEquipmentRecord(Integer equipId, String equipName) {
        super(RoomEquipment.ROOM_EQUIPMENT);

        set(0, equipId);
        set(1, equipName);
    }
}
