/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db.tables.records;


import de.rubeen.bsc.entities.db.enums.Calprovider;
import de.rubeen.bsc.entities.db.tables.Room;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomRecord extends UpdatableRecordImpl<RoomRecord> implements Record5<Integer, String, Integer, Calprovider, String> {

    private static final long serialVersionUID = 304770790;

    /**
     * Setter for <code>public.room.room_id</code>.
     */
    public void setRoomId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.room.room_id</code>.
     */
    public Integer getRoomId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.room.room_name</code>.
     */
    public void setRoomName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.room.room_name</code>.
     */
    public String getRoomName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.room.room_size</code>.
     */
    public void setRoomSize(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.room.room_size</code>.
     */
    public Integer getRoomSize() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.room.provider</code>.
     */
    public void setProvider(Calprovider value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.room.provider</code>.
     */
    public Calprovider getProvider() {
        return (Calprovider) get(3);
    }

    /**
     * Setter for <code>public.room.calendarid</code>.
     */
    public void setCalendarid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.room.calendarid</code>.
     */
    public String getCalendarid() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Calprovider, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Calprovider, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Room.ROOM.ROOM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Room.ROOM.ROOM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Room.ROOM.ROOM_SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Calprovider> field4() {
        return Room.ROOM.PROVIDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Room.ROOM.CALENDARID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getRoomId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRoomName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRoomSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Calprovider component4() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCalendarid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRoomId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRoomName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRoomSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Calprovider value4() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCalendarid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomRecord value1(Integer value) {
        setRoomId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomRecord value2(String value) {
        setRoomName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomRecord value3(Integer value) {
        setRoomSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomRecord value4(Calprovider value) {
        setProvider(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomRecord value5(String value) {
        setCalendarid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomRecord values(Integer value1, String value2, Integer value3, Calprovider value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoomRecord
     */
    public RoomRecord() {
        super(Room.ROOM);
    }

    /**
     * Create a detached, initialised RoomRecord
     */
    public RoomRecord(Integer roomId, String roomName, Integer roomSize, Calprovider provider, String calendarid) {
        super(Room.ROOM);

        set(0, roomId);
        set(1, roomName);
        set(2, roomSize);
        set(3, provider);
        set(4, calendarid);
    }
}
