/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db.tables.records;


import de.rubeen.bsc.entities.db.tables.Workinghours;

import java.sql.Time;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkinghoursRecord extends UpdatableRecordImpl<WorkinghoursRecord> implements Record11<Integer, Integer, Time, Time, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean> {

    private static final long serialVersionUID = -1418412165;

    /**
     * Setter for <code>public.workinghours.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.workinghours.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.workinghours.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.workinghours.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.workinghours.starttime</code>.
     */
    public void setStarttime(Time value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.workinghours.starttime</code>.
     */
    public Time getStarttime() {
        return (Time) get(2);
    }

    /**
     * Setter for <code>public.workinghours.endtime</code>.
     */
    public void setEndtime(Time value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.workinghours.endtime</code>.
     */
    public Time getEndtime() {
        return (Time) get(3);
    }

    /**
     * Setter for <code>public.workinghours.monday</code>.
     */
    public void setMonday(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.workinghours.monday</code>.
     */
    public Boolean getMonday() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.workinghours.tuesday</code>.
     */
    public void setTuesday(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.workinghours.tuesday</code>.
     */
    public Boolean getTuesday() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.workinghours.wednesday</code>.
     */
    public void setWednesday(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.workinghours.wednesday</code>.
     */
    public Boolean getWednesday() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.workinghours.thursday</code>.
     */
    public void setThursday(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.workinghours.thursday</code>.
     */
    public Boolean getThursday() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.workinghours.friday</code>.
     */
    public void setFriday(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.workinghours.friday</code>.
     */
    public Boolean getFriday() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.workinghours.saturday</code>.
     */
    public void setSaturday(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.workinghours.saturday</code>.
     */
    public Boolean getSaturday() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.workinghours.sunday</code>.
     */
    public void setSunday(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.workinghours.sunday</code>.
     */
    public Boolean getSunday() {
        return (Boolean) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, Time, Time, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, Time, Time, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Workinghours.WORKINGHOURS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Workinghours.WORKINGHOURS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Time> field3() {
        return Workinghours.WORKINGHOURS.STARTTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Time> field4() {
        return Workinghours.WORKINGHOURS.ENDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Workinghours.WORKINGHOURS.MONDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return Workinghours.WORKINGHOURS.TUESDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return Workinghours.WORKINGHOURS.WEDNESDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Workinghours.WORKINGHOURS.THURSDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return Workinghours.WORKINGHOURS.FRIDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return Workinghours.WORKINGHOURS.SATURDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return Workinghours.WORKINGHOURS.SUNDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time component3() {
        return getStarttime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time component4() {
        return getEndtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getMonday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getTuesday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getWednesday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getThursday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getFriday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component10() {
        return getSaturday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component11() {
        return getSunday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time value3() {
        return getStarttime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time value4() {
        return getEndtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getMonday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getTuesday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getWednesday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getThursday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getFriday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getSaturday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getSunday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkinghoursRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkinghoursRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkinghoursRecord value3(Time value) {
        setStarttime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkinghoursRecord value4(Time value) {
        setEndtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkinghoursRecord value5(Boolean value) {
        setMonday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkinghoursRecord value6(Boolean value) {
        setTuesday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkinghoursRecord value7(Boolean value) {
        setWednesday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkinghoursRecord value8(Boolean value) {
        setThursday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkinghoursRecord value9(Boolean value) {
        setFriday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkinghoursRecord value10(Boolean value) {
        setSaturday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkinghoursRecord value11(Boolean value) {
        setSunday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkinghoursRecord values(Integer value1, Integer value2, Time value3, Time value4, Boolean value5, Boolean value6, Boolean value7, Boolean value8, Boolean value9, Boolean value10, Boolean value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkinghoursRecord
     */
    public WorkinghoursRecord() {
        super(Workinghours.WORKINGHOURS);
    }

    /**
     * Create a detached, initialised WorkinghoursRecord
     */
    public WorkinghoursRecord(Integer id, Integer userId, Time starttime, Time endtime, Boolean monday, Boolean tuesday, Boolean wednesday, Boolean thursday, Boolean friday, Boolean saturday, Boolean sunday) {
        super(Workinghours.WORKINGHOURS);

        set(0, id);
        set(1, userId);
        set(2, starttime);
        set(3, endtime);
        set(4, monday);
        set(5, tuesday);
        set(6, wednesday);
        set(7, thursday);
        set(8, friday);
        set(9, saturday);
        set(10, sunday);
    }
}
