/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db;


import de.rubeen.bsc.entities.db.tables.Appuser;
import de.rubeen.bsc.entities.db.tables.Calendar;
import de.rubeen.bsc.entities.db.tables.Credential;
import de.rubeen.bsc.entities.db.tables.Room;
import de.rubeen.bsc.entities.db.tables.RoomEquipment;
import de.rubeen.bsc.entities.db.tables.RoomRoomEquipment;
import de.rubeen.bsc.entities.db.tables.Workinghours;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index APPUSER_PKEY = Indexes0.APPUSER_PKEY;
    public static final Index CALENDAR_PKEY = Indexes0.CALENDAR_PKEY;
    public static final Index CREDENTIAL_PKEY = Indexes0.CREDENTIAL_PKEY;
    public static final Index ROOM_PKEY = Indexes0.ROOM_PKEY;
    public static final Index ROOM_EQUIPMENT_PKEY = Indexes0.ROOM_EQUIPMENT_PKEY;
    public static final Index ROOM_ROOM_EQUIPMENT_PKEY = Indexes0.ROOM_ROOM_EQUIPMENT_PKEY;
    public static final Index WORKINGHOURS_PKEY = Indexes0.WORKINGHOURS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index APPUSER_PKEY = Internal.createIndex("appuser_pkey", Appuser.APPUSER, new OrderField[] { Appuser.APPUSER.ID }, true);
        public static Index CALENDAR_PKEY = Internal.createIndex("calendar_pkey", Calendar.CALENDAR, new OrderField[] { Calendar.CALENDAR.ID }, true);
        public static Index CREDENTIAL_PKEY = Internal.createIndex("credential_pkey", Credential.CREDENTIAL, new OrderField[] { Credential.CREDENTIAL.USER_ID }, true);
        public static Index ROOM_PKEY = Internal.createIndex("room_pkey", Room.ROOM, new OrderField[] { Room.ROOM.ROOM_ID }, true);
        public static Index ROOM_EQUIPMENT_PKEY = Internal.createIndex("room_equipment_pkey", RoomEquipment.ROOM_EQUIPMENT, new OrderField[] { RoomEquipment.ROOM_EQUIPMENT.EQUIP_ID }, true);
        public static Index ROOM_ROOM_EQUIPMENT_PKEY = Internal.createIndex("room_room_equipment_pkey", RoomRoomEquipment.ROOM_ROOM_EQUIPMENT, new OrderField[] { RoomRoomEquipment.ROOM_ROOM_EQUIPMENT.ROOM_ID, RoomRoomEquipment.ROOM_ROOM_EQUIPMENT.ROOM_EQUIPMENT_ID }, true);
        public static Index WORKINGHOURS_PKEY = Internal.createIndex("workinghours_pkey", Workinghours.WORKINGHOURS, new OrderField[] { Workinghours.WORKINGHOURS.ID }, true);
    }
}
