/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db;


import de.rubeen.bsc.entities.db.tables.Appuser;
import de.rubeen.bsc.entities.db.tables.Calendar;
import de.rubeen.bsc.entities.db.tables.Credential;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index APPUSER_PKEY = Indexes0.APPUSER_PKEY;
    public static final Index CALENDAR_PKEY = Indexes0.CALENDAR_PKEY;
    public static final Index CREDENTIAL_PKEY = Indexes0.CREDENTIAL_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index APPUSER_PKEY = Internal.createIndex("appuser_pkey", Appuser.APPUSER, new OrderField[] { Appuser.APPUSER.ID }, true);
        public static Index CALENDAR_PKEY = Internal.createIndex("calendar_pkey", Calendar.CALENDAR, new OrderField[] { Calendar.CALENDAR.ID }, true);
        public static Index CREDENTIAL_PKEY = Internal.createIndex("credential_pkey", Credential.CREDENTIAL, new OrderField[] { Credential.CREDENTIAL.ID }, true);
    }
}
