/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db;


import de.rubeen.bsc.entities.db.tables.Appuser;
import de.rubeen.bsc.entities.db.tables.Credential;
import de.rubeen.bsc.entities.db.tables.records.AppuserRecord;
import de.rubeen.bsc.entities.db.tables.records.CredentialRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppuserRecord> APPUSER_PKEY = UniqueKeys0.APPUSER_PKEY;
    public static final UniqueKey<CredentialRecord> CREDENTIAL_PKEY = UniqueKeys0.CREDENTIAL_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CredentialRecord, AppuserRecord> CREDENTIAL__CREDENTIAL_USERS_ID_FKEY = ForeignKeys0.CREDENTIAL__CREDENTIAL_USERS_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AppuserRecord> APPUSER_PKEY = Internal.createUniqueKey(Appuser.APPUSER, "appuser_pkey", Appuser.APPUSER.ID);
        public static final UniqueKey<CredentialRecord> CREDENTIAL_PKEY = Internal.createUniqueKey(Credential.CREDENTIAL, "credential_pkey", Credential.CREDENTIAL.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<CredentialRecord, AppuserRecord> CREDENTIAL__CREDENTIAL_USERS_ID_FKEY = Internal.createForeignKey(de.rubeen.bsc.entities.db.Keys.APPUSER_PKEY, Credential.CREDENTIAL, "credential__credential_users_id_fkey", Credential.CREDENTIAL.USERS_ID);
    }
}
