/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db;


import de.rubeen.bsc.entities.db.tables.Appuser;
import de.rubeen.bsc.entities.db.tables.Calendar;
import de.rubeen.bsc.entities.db.tables.Credential;
import de.rubeen.bsc.entities.db.tables.Room;
import de.rubeen.bsc.entities.db.tables.RoomEquipment;
import de.rubeen.bsc.entities.db.tables.RoomRoomEquipment;
import de.rubeen.bsc.entities.db.tables.Workinghours;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 586232322;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.appuser</code>.
     */
    public final Appuser APPUSER = de.rubeen.bsc.entities.db.tables.Appuser.APPUSER;

    /**
     * The table <code>public.calendar</code>.
     */
    public final Calendar CALENDAR = de.rubeen.bsc.entities.db.tables.Calendar.CALENDAR;

    /**
     * The table <code>public.credential</code>.
     */
    public final Credential CREDENTIAL = de.rubeen.bsc.entities.db.tables.Credential.CREDENTIAL;

    /**
     * The table <code>public.room</code>.
     */
    public final Room ROOM = de.rubeen.bsc.entities.db.tables.Room.ROOM;

    /**
     * The table <code>public.room_equipment</code>.
     */
    public final RoomEquipment ROOM_EQUIPMENT = de.rubeen.bsc.entities.db.tables.RoomEquipment.ROOM_EQUIPMENT;

    /**
     * The table <code>public.room_room_equipment</code>.
     */
    public final RoomRoomEquipment ROOM_ROOM_EQUIPMENT = de.rubeen.bsc.entities.db.tables.RoomRoomEquipment.ROOM_ROOM_EQUIPMENT;

    /**
     * The table <code>public.workinghours</code>.
     */
    public final Workinghours WORKINGHOURS = de.rubeen.bsc.entities.db.tables.Workinghours.WORKINGHOURS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.APPUSER_ID_SEQ,
            Sequences.CALENDAR_ID_SEQ,
            Sequences.ROOM_EQUIPMENT_EQUIP_ID_SEQ,
            Sequences.ROOM_ROOM_ID_SEQ,
            Sequences.WORKINGHOURS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Appuser.APPUSER,
            Calendar.CALENDAR,
            Credential.CREDENTIAL,
            Room.ROOM,
            RoomEquipment.ROOM_EQUIPMENT,
            RoomRoomEquipment.ROOM_ROOM_EQUIPMENT,
            Workinghours.WORKINGHOURS);
    }
}
