/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.appuser_id_seq</code>
     */
    public static final Sequence<Integer> APPUSER_ID_SEQ = new SequenceImpl<Integer>("appuser_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.calendar_id_seq</code>
     */
    public static final Sequence<Integer> CALENDAR_ID_SEQ = new SequenceImpl<Integer>("calendar_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.room_equipment_equip_id_seq</code>
     */
    public static final Sequence<Integer> ROOM_EQUIPMENT_EQUIP_ID_SEQ = new SequenceImpl<Integer>("room_equipment_equip_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.room_room_id_seq</code>
     */
    public static final Sequence<Integer> ROOM_ROOM_ID_SEQ = new SequenceImpl<Integer>("room_room_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.workinghours_id_seq</code>
     */
    public static final Sequence<Integer> WORKINGHOURS_ID_SEQ = new SequenceImpl<Integer>("workinghours_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
