/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db;


import de.rubeen.bsc.entities.db.tables.Appuser;
import de.rubeen.bsc.entities.db.tables.Calendar;
import de.rubeen.bsc.entities.db.tables.Credential;
import de.rubeen.bsc.entities.db.tables.Room;
import de.rubeen.bsc.entities.db.tables.RoomEquipment;
import de.rubeen.bsc.entities.db.tables.RoomRoomEquipment;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.appuser</code>.
     */
    public static final Appuser APPUSER = de.rubeen.bsc.entities.db.tables.Appuser.APPUSER;

    /**
     * The table <code>public.calendar</code>.
     */
    public static final Calendar CALENDAR = de.rubeen.bsc.entities.db.tables.Calendar.CALENDAR;

    /**
     * The table <code>public.credential</code>.
     */
    public static final Credential CREDENTIAL = de.rubeen.bsc.entities.db.tables.Credential.CREDENTIAL;

    /**
     * The table <code>public.room</code>.
     */
    public static final Room ROOM = de.rubeen.bsc.entities.db.tables.Room.ROOM;

    /**
     * The table <code>public.room_equipment</code>.
     */
    public static final RoomEquipment ROOM_EQUIPMENT = de.rubeen.bsc.entities.db.tables.RoomEquipment.ROOM_EQUIPMENT;

    /**
     * The table <code>public.room_room_equipment</code>.
     */
    public static final RoomRoomEquipment ROOM_ROOM_EQUIPMENT = de.rubeen.bsc.entities.db.tables.RoomRoomEquipment.ROOM_ROOM_EQUIPMENT;
}
