/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db.tables;


import de.rubeen.bsc.entities.db.Indexes;
import de.rubeen.bsc.entities.db.Keys;
import de.rubeen.bsc.entities.db.Public;
import de.rubeen.bsc.entities.db.tables.records.AppuserRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Appuser extends TableImpl<AppuserRecord> {

    private static final long serialVersionUID = 973961623;

    /**
     * The reference instance of <code>public.appuser</code>
     */
    public static final Appuser APPUSER = new Appuser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppuserRecord> getRecordType() {
        return AppuserRecord.class;
    }

    /**
     * The column <code>public.appuser.id</code>.
     */
    public final TableField<AppuserRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('appuser_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.appuser.password</code>.
     */
    public final TableField<AppuserRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.appuser.name</code>.
     */
    public final TableField<AppuserRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.appuser.mail</code>.
     */
    public final TableField<AppuserRecord, String> MAIL = createField("mail", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.appuser.position</code>.
     */
    public final TableField<AppuserRecord, String> POSITION = createField("position", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.appuser.avatar</code>.
     */
    public final TableField<AppuserRecord, String> AVATAR = createField("avatar", org.jooq.impl.SQLDataType.VARCHAR(500).nullable(false).defaultValue(org.jooq.impl.DSL.field("'https://randomuser.me/api/portraits/lego/1.jpg'::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>public.appuser</code> table reference
     */
    public Appuser() {
        this(DSL.name("appuser"), null);
    }

    /**
     * Create an aliased <code>public.appuser</code> table reference
     */
    public Appuser(String alias) {
        this(DSL.name(alias), APPUSER);
    }

    /**
     * Create an aliased <code>public.appuser</code> table reference
     */
    public Appuser(Name alias) {
        this(alias, APPUSER);
    }

    private Appuser(Name alias, Table<AppuserRecord> aliased) {
        this(alias, aliased, null);
    }

    private Appuser(Name alias, Table<AppuserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Appuser(Table<O> child, ForeignKey<O, AppuserRecord> key) {
        super(child, key, APPUSER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.APPUSER_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AppuserRecord, Integer> getIdentity() {
        return Keys.IDENTITY_APPUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AppuserRecord> getPrimaryKey() {
        return Keys.APPUSER_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AppuserRecord>> getKeys() {
        return Arrays.<UniqueKey<AppuserRecord>>asList(Keys.APPUSER_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Appuser as(String alias) {
        return new Appuser(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Appuser as(Name alias) {
        return new Appuser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Appuser rename(String name) {
        return new Appuser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Appuser rename(Name name) {
        return new Appuser(name, null);
    }
}
