/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db.tables;


import de.rubeen.bsc.entities.db.Indexes;
import de.rubeen.bsc.entities.db.Keys;
import de.rubeen.bsc.entities.db.Public;
import de.rubeen.bsc.entities.db.enums.Calprovider;
import de.rubeen.bsc.entities.db.tables.records.CalendarRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Calendar extends TableImpl<CalendarRecord> {

    private static final long serialVersionUID = 1280476306;

    /**
     * The reference instance of <code>public.calendar</code>
     */
    public static final Calendar CALENDAR = new Calendar();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CalendarRecord> getRecordType() {
        return CalendarRecord.class;
    }

    /**
     * The column <code>public.calendar.id</code>.
     */
    public final TableField<CalendarRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('calendar_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.calendar.calendarid</code>.
     */
    public final TableField<CalendarRecord, String> CALENDARID = createField("calendarid", org.jooq.impl.SQLDataType.VARCHAR(1000).nullable(false), this, "");

    /**
     * The column <code>public.calendar.activated</code>.
     */
    public final TableField<CalendarRecord, Boolean> ACTIVATED = createField("activated", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.calendar.provider</code>.
     */
    public final TableField<CalendarRecord, Calprovider> PROVIDER = createField("provider", org.jooq.impl.SQLDataType.VARCHAR.nullable(false).asEnumDataType(de.rubeen.bsc.entities.db.enums.Calprovider.class), this, "");

    /**
     * The column <code>public.calendar.user_id</code>.
     */
    public final TableField<CalendarRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.calendar.isdefault</code>.
     */
    public final TableField<CalendarRecord, Boolean> ISDEFAULT = createField("isdefault", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>public.calendar</code> table reference
     */
    public Calendar() {
        this(DSL.name("calendar"), null);
    }

    /**
     * Create an aliased <code>public.calendar</code> table reference
     */
    public Calendar(String alias) {
        this(DSL.name(alias), CALENDAR);
    }

    /**
     * Create an aliased <code>public.calendar</code> table reference
     */
    public Calendar(Name alias) {
        this(alias, CALENDAR);
    }

    private Calendar(Name alias, Table<CalendarRecord> aliased) {
        this(alias, aliased, null);
    }

    private Calendar(Name alias, Table<CalendarRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Calendar(Table<O> child, ForeignKey<O, CalendarRecord> key) {
        super(child, key, CALENDAR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CALENDAR_ISDEFAULT_EXCL, Indexes.CALENDAR_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CalendarRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CALENDAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CalendarRecord> getPrimaryKey() {
        return Keys.CALENDAR_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CalendarRecord>> getKeys() {
        return Arrays.<UniqueKey<CalendarRecord>>asList(Keys.CALENDAR_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CalendarRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CalendarRecord, ?>>asList(Keys.CALENDAR__CALENDAR_USER_ID_FKEY);
    }

    public Appuser appuser() {
        return new Appuser(this, Keys.CALENDAR__CALENDAR_USER_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Calendar as(String alias) {
        return new Calendar(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Calendar as(Name alias) {
        return new Calendar(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Calendar rename(String name) {
        return new Calendar(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Calendar rename(Name name) {
        return new Calendar(name, null);
    }
}
