/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db.tables;


import de.rubeen.bsc.entities.db.Indexes;
import de.rubeen.bsc.entities.db.Keys;
import de.rubeen.bsc.entities.db.Public;
import de.rubeen.bsc.entities.db.tables.records.RoomEquipmentRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomEquipment extends TableImpl<RoomEquipmentRecord> {

    private static final long serialVersionUID = -442611658;

    /**
     * The reference instance of <code>public.room_equipment</code>
     */
    public static final RoomEquipment ROOM_EQUIPMENT = new RoomEquipment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomEquipmentRecord> getRecordType() {
        return RoomEquipmentRecord.class;
    }

    /**
     * The column <code>public.room_equipment.equip_id</code>.
     */
    public final TableField<RoomEquipmentRecord, Integer> EQUIP_ID = createField("equip_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('room_equipment_equip_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.room_equipment.equip_name</code>.
     */
    public final TableField<RoomEquipmentRecord, String> EQUIP_NAME = createField("equip_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>public.room_equipment</code> table reference
     */
    public RoomEquipment() {
        this(DSL.name("room_equipment"), null);
    }

    /**
     * Create an aliased <code>public.room_equipment</code> table reference
     */
    public RoomEquipment(String alias) {
        this(DSL.name(alias), ROOM_EQUIPMENT);
    }

    /**
     * Create an aliased <code>public.room_equipment</code> table reference
     */
    public RoomEquipment(Name alias) {
        this(alias, ROOM_EQUIPMENT);
    }

    private RoomEquipment(Name alias, Table<RoomEquipmentRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoomEquipment(Name alias, Table<RoomEquipmentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RoomEquipment(Table<O> child, ForeignKey<O, RoomEquipmentRecord> key) {
        super(child, key, ROOM_EQUIPMENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ROOM_EQUIPMENT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RoomEquipmentRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ROOM_EQUIPMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RoomEquipmentRecord> getPrimaryKey() {
        return Keys.ROOM_EQUIPMENT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RoomEquipmentRecord>> getKeys() {
        return Arrays.<UniqueKey<RoomEquipmentRecord>>asList(Keys.ROOM_EQUIPMENT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomEquipment as(String alias) {
        return new RoomEquipment(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomEquipment as(Name alias) {
        return new RoomEquipment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomEquipment rename(String name) {
        return new RoomEquipment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomEquipment rename(Name name) {
        return new RoomEquipment(name, null);
    }
}
