/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db.tables;


import de.rubeen.bsc.entities.db.Indexes;
import de.rubeen.bsc.entities.db.Keys;
import de.rubeen.bsc.entities.db.Public;
import de.rubeen.bsc.entities.db.enums.Calprovider;
import de.rubeen.bsc.entities.db.tables.records.RoomRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Room extends TableImpl<RoomRecord> {

    private static final long serialVersionUID = 549937756;

    /**
     * The reference instance of <code>public.room</code>
     */
    public static final Room ROOM = new Room();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomRecord> getRecordType() {
        return RoomRecord.class;
    }

    /**
     * The column <code>public.room.room_id</code>.
     */
    public final TableField<RoomRecord, Integer> ROOM_ID = createField("room_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('room_room_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.room.room_name</code>.
     */
    public final TableField<RoomRecord, String> ROOM_NAME = createField("room_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.room.room_size</code>.
     */
    public final TableField<RoomRecord, Integer> ROOM_SIZE = createField("room_size", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.room.provider</code>.
     */
    public final TableField<RoomRecord, Calprovider> PROVIDER = createField("provider", org.jooq.impl.SQLDataType.VARCHAR.nullable(false).asEnumDataType(de.rubeen.bsc.entities.db.enums.Calprovider.class), this, "");

    /**
     * The column <code>public.room.calendarid</code>.
     */
    public final TableField<RoomRecord, String> CALENDARID = createField("calendarid", org.jooq.impl.SQLDataType.VARCHAR(1000).nullable(false), this, "");

    /**
     * Create a <code>public.room</code> table reference
     */
    public Room() {
        this(DSL.name("room"), null);
    }

    /**
     * Create an aliased <code>public.room</code> table reference
     */
    public Room(String alias) {
        this(DSL.name(alias), ROOM);
    }

    /**
     * Create an aliased <code>public.room</code> table reference
     */
    public Room(Name alias) {
        this(alias, ROOM);
    }

    private Room(Name alias, Table<RoomRecord> aliased) {
        this(alias, aliased, null);
    }

    private Room(Name alias, Table<RoomRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Room(Table<O> child, ForeignKey<O, RoomRecord> key) {
        super(child, key, ROOM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ROOM_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RoomRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RoomRecord> getPrimaryKey() {
        return Keys.ROOM_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RoomRecord>> getKeys() {
        return Arrays.<UniqueKey<RoomRecord>>asList(Keys.ROOM_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Room as(String alias) {
        return new Room(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Room as(Name alias) {
        return new Room(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Room rename(String name) {
        return new Room(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Room rename(Name name) {
        return new Room(name, null);
    }
}
