/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db.tables;


import de.rubeen.bsc.entities.db.Indexes;
import de.rubeen.bsc.entities.db.Keys;
import de.rubeen.bsc.entities.db.Public;
import de.rubeen.bsc.entities.db.tables.records.RoomRoomEquipmentRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomRoomEquipment extends TableImpl<RoomRoomEquipmentRecord> {

    private static final long serialVersionUID = 1937156952;

    /**
     * The reference instance of <code>public.room_room_equipment</code>
     */
    public static final RoomRoomEquipment ROOM_ROOM_EQUIPMENT = new RoomRoomEquipment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomRoomEquipmentRecord> getRecordType() {
        return RoomRoomEquipmentRecord.class;
    }

    /**
     * The column <code>public.room_room_equipment.room_id</code>.
     */
    public final TableField<RoomRoomEquipmentRecord, Integer> ROOM_ID = createField("room_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.room_room_equipment.room_equipment_id</code>.
     */
    public final TableField<RoomRoomEquipmentRecord, Integer> ROOM_EQUIPMENT_ID = createField("room_equipment_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.room_room_equipment</code> table reference
     */
    public RoomRoomEquipment() {
        this(DSL.name("room_room_equipment"), null);
    }

    /**
     * Create an aliased <code>public.room_room_equipment</code> table reference
     */
    public RoomRoomEquipment(String alias) {
        this(DSL.name(alias), ROOM_ROOM_EQUIPMENT);
    }

    /**
     * Create an aliased <code>public.room_room_equipment</code> table reference
     */
    public RoomRoomEquipment(Name alias) {
        this(alias, ROOM_ROOM_EQUIPMENT);
    }

    private RoomRoomEquipment(Name alias, Table<RoomRoomEquipmentRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoomRoomEquipment(Name alias, Table<RoomRoomEquipmentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RoomRoomEquipment(Table<O> child, ForeignKey<O, RoomRoomEquipmentRecord> key) {
        super(child, key, ROOM_ROOM_EQUIPMENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ROOM_ROOMEQUIPMENT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RoomRoomEquipmentRecord> getPrimaryKey() {
        return Keys.ROOM_ROOMEQUIPMENT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RoomRoomEquipmentRecord>> getKeys() {
        return Arrays.<UniqueKey<RoomRoomEquipmentRecord>>asList(Keys.ROOM_ROOMEQUIPMENT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RoomRoomEquipmentRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RoomRoomEquipmentRecord, ?>>asList(Keys.ROOM_ROOM_EQUIPMENT__ROOM_ROOM_EQUIPMENT_ROOM_ID_FKEY, Keys.ROOM_ROOM_EQUIPMENT__ROOM_ROOM_EQUIPMENT_ROOM_EQUIPMENT_ID_FKEY);
    }

    public Room room() {
        return new Room(this, Keys.ROOM_ROOM_EQUIPMENT__ROOM_ROOM_EQUIPMENT_ROOM_ID_FKEY);
    }

    public RoomEquipment roomEquipment() {
        return new RoomEquipment(this, Keys.ROOM_ROOM_EQUIPMENT__ROOM_ROOM_EQUIPMENT_ROOM_EQUIPMENT_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomRoomEquipment as(String alias) {
        return new RoomRoomEquipment(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomRoomEquipment as(Name alias) {
        return new RoomRoomEquipment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomRoomEquipment rename(String name) {
        return new RoomRoomEquipment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomRoomEquipment rename(Name name) {
        return new RoomRoomEquipment(name, null);
    }
}
