/*
 * This file is generated by jOOQ.
 */
package de.rubeen.bsc.entities.db.tables;


import de.rubeen.bsc.entities.db.Indexes;
import de.rubeen.bsc.entities.db.Keys;
import de.rubeen.bsc.entities.db.Public;
import de.rubeen.bsc.entities.db.tables.records.WorkinghoursRecord;

import java.sql.Time;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Workinghours extends TableImpl<WorkinghoursRecord> {

    private static final long serialVersionUID = 606206519;

    /**
     * The reference instance of <code>public.workinghours</code>
     */
    public static final Workinghours WORKINGHOURS = new Workinghours();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorkinghoursRecord> getRecordType() {
        return WorkinghoursRecord.class;
    }

    /**
     * The column <code>public.workinghours.id</code>.
     */
    public final TableField<WorkinghoursRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('workinghours_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.workinghours.user_fk</code>.
     */
    public final TableField<WorkinghoursRecord, Integer> USER_FK = createField("user_fk", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.workinghours.starttime</code>.
     */
    public final TableField<WorkinghoursRecord, Time> STARTTIME = createField("starttime", org.jooq.impl.SQLDataType.TIME.nullable(false), this, "");

    /**
     * The column <code>public.workinghours.endtime</code>.
     */
    public final TableField<WorkinghoursRecord, Time> ENDTIME = createField("endtime", org.jooq.impl.SQLDataType.TIME.nullable(false), this, "");

    /**
     * The column <code>public.workinghours.monday</code>.
     */
    public final TableField<WorkinghoursRecord, Boolean> MONDAY = createField("monday", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.workinghours.tuesday</code>.
     */
    public final TableField<WorkinghoursRecord, Boolean> TUESDAY = createField("tuesday", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.workinghours.wednesday</code>.
     */
    public final TableField<WorkinghoursRecord, Boolean> WEDNESDAY = createField("wednesday", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.workinghours.thursday</code>.
     */
    public final TableField<WorkinghoursRecord, Boolean> THURSDAY = createField("thursday", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.workinghours.friday</code>.
     */
    public final TableField<WorkinghoursRecord, Boolean> FRIDAY = createField("friday", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.workinghours.saturday</code>.
     */
    public final TableField<WorkinghoursRecord, Boolean> SATURDAY = createField("saturday", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.workinghours.sunday</code>.
     */
    public final TableField<WorkinghoursRecord, Boolean> SUNDAY = createField("sunday", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>public.workinghours</code> table reference
     */
    public Workinghours() {
        this(DSL.name("workinghours"), null);
    }

    /**
     * Create an aliased <code>public.workinghours</code> table reference
     */
    public Workinghours(String alias) {
        this(DSL.name(alias), WORKINGHOURS);
    }

    /**
     * Create an aliased <code>public.workinghours</code> table reference
     */
    public Workinghours(Name alias) {
        this(alias, WORKINGHOURS);
    }

    private Workinghours(Name alias, Table<WorkinghoursRecord> aliased) {
        this(alias, aliased, null);
    }

    private Workinghours(Name alias, Table<WorkinghoursRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Workinghours(Table<O> child, ForeignKey<O, WorkinghoursRecord> key) {
        super(child, key, WORKINGHOURS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.WORKINGHOURS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WorkinghoursRecord, Integer> getIdentity() {
        return Keys.IDENTITY_WORKINGHOURS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WorkinghoursRecord> getPrimaryKey() {
        return Keys.WORKINGHOURS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WorkinghoursRecord>> getKeys() {
        return Arrays.<UniqueKey<WorkinghoursRecord>>asList(Keys.WORKINGHOURS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<WorkinghoursRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WorkinghoursRecord, ?>>asList(Keys.WORKINGHOURS__WORKINGHOURS_USER_FK_FKEY);
    }

    public Appuser appuser() {
        return new Appuser(this, Keys.WORKINGHOURS__WORKINGHOURS_USER_FK_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Workinghours as(String alias) {
        return new Workinghours(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Workinghours as(Name alias) {
        return new Workinghours(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Workinghours rename(String name) {
        return new Workinghours(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Workinghours rename(Name name) {
        return new Workinghours(name, null);
    }
}
