logging.level.root=debug

google.client.client-id=1050999188422-skivv5q1g1juskgc28o3ndde2t8ibuk9.apps.googleusercontent.com
google.client.client-secret=6_moFdZ5gce-iqn9dgQSu7aS

google.client.access-token-uri=https://www.googleapis.com/oauth2/v3/token
google.client.user-authorization-uri=https://accounts.google.com/o/oauth2/auth?access_type=offline&prompt=consent
google.client.client-authentication-scheme=query
google.client.scope=profile,email,https://www.googleapis.com/auth/calendar
google.resource.user-info-uri=https://www.googleapis.com/oauth2/v2/userinfo
google.resource.prefer-token-info=true
google.client.redirectUri=https://localhost:3333/api/auth-google

webapp.url=https://localhost:3333

server.port=8443
server.ssl.key-store=keystore.jks
server.ssl.key-store-password=SX.PvW;Zwy.6"5U[_HUDDh;r
server.ssl.key-store-type=JKS
server.ssl.key-alias=tomcat

database.url=jdbc:postgresql://localhost:5432/testdatabase
database.user=testuser
database.pass=testpass